using System.Collections.Generic;
using MODAPI_LangTool.Models;

namespace MODAPI_LangTool.Helpers
{
    public static class IsoCountryList
    {
        // ISO 3166-1 alpha-2 전체 목록 (249개)
        // IsoCode(소문자), Name(영문), LangCode(기본 언어파일 코드)
        public static readonly List<IsoCountry> All = new List<IsoCountry>
        {
            new IsoCountry { IsoCode="af", Name="Afghanistan",                              LangCode="AF" },
            new IsoCountry { IsoCode="al", Name="Albania",                                  LangCode="AL" },
            new IsoCountry { IsoCode="dz", Name="Algeria",                                  LangCode="AR-DZ" },
            new IsoCountry { IsoCode="ad", Name="Andorra",                                  LangCode="AD" },
            new IsoCountry { IsoCode="ao", Name="Angola",                                   LangCode="AO" },
            new IsoCountry { IsoCode="ag", Name="Antigua and Barbuda",                      LangCode="AG" },
            new IsoCountry { IsoCode="ar", Name="Argentina",                                LangCode="AR" },
            new IsoCountry { IsoCode="am", Name="Armenia",                                  LangCode="AM" },
            new IsoCountry { IsoCode="au", Name="Australia",                                LangCode="EN-AU" },
            new IsoCountry { IsoCode="at", Name="Austria",                                  LangCode="DE-AT" },
            new IsoCountry { IsoCode="az", Name="Azerbaijan",                               LangCode="AZ" },
            new IsoCountry { IsoCode="bs", Name="Bahamas",                                  LangCode="BS" },
            new IsoCountry { IsoCode="bh", Name="Bahrain",                                  LangCode="AR-BH" },
            new IsoCountry { IsoCode="bd", Name="Bangladesh",                               LangCode="BN" },
            new IsoCountry { IsoCode="bb", Name="Barbados",                                 LangCode="BB" },
            new IsoCountry { IsoCode="by", Name="Belarus",                                  LangCode="BE" },
            new IsoCountry { IsoCode="be", Name="Belgium",                                  LangCode="NL-BE" },
            new IsoCountry { IsoCode="bz", Name="Belize",                                   LangCode="BZ" },
            new IsoCountry { IsoCode="bj", Name="Benin",                                    LangCode="BJ" },
            new IsoCountry { IsoCode="bt", Name="Bhutan",                                   LangCode="BT" },
            new IsoCountry { IsoCode="bo", Name="Bolivia",                                  LangCode="ES-BO" },
            new IsoCountry { IsoCode="ba", Name="Bosnia and Herzegovina",                   LangCode="BS-BA" },
            new IsoCountry { IsoCode="bw", Name="Botswana",                                 LangCode="BW" },
            new IsoCountry { IsoCode="br", Name="Brazil",                                   LangCode="PT-BR" },
            new IsoCountry { IsoCode="bn", Name="Brunei",                                   LangCode="MS-BN" },
            new IsoCountry { IsoCode="bg", Name="Bulgaria",                                 LangCode="BG" },
            new IsoCountry { IsoCode="bf", Name="Burkina Faso",                             LangCode="BF" },
            new IsoCountry { IsoCode="bi", Name="Burundi",                                  LangCode="BI" },
            new IsoCountry { IsoCode="cv", Name="Cabo Verde",                               LangCode="CV" },
            new IsoCountry { IsoCode="kh", Name="Cambodia",                                 LangCode="KM" },
            new IsoCountry { IsoCode="cm", Name="Cameroon",                                 LangCode="CM" },
            new IsoCountry { IsoCode="ca", Name="Canada",                                   LangCode="EN-CA" },
            new IsoCountry { IsoCode="cf", Name="Central African Republic",                 LangCode="CF" },
            new IsoCountry { IsoCode="td", Name="Chad",                                     LangCode="TD" },
            new IsoCountry { IsoCode="cl", Name="Chile",                                    LangCode="ES-CL" },
            new IsoCountry { IsoCode="cn", Name="China",                                    LangCode="ZH" },
            new IsoCountry { IsoCode="co", Name="Colombia",                                 LangCode="ES-CO" },
            new IsoCountry { IsoCode="km", Name="Comoros",                                  LangCode="KM" },
            new IsoCountry { IsoCode="cg", Name="Congo",                                    LangCode="CG" },
            new IsoCountry { IsoCode="cd", Name="Congo (DRC)",                              LangCode="CD" },
            new IsoCountry { IsoCode="cr", Name="Costa Rica",                               LangCode="ES-CR" },
            new IsoCountry { IsoCode="hr", Name="Croatia",                                  LangCode="HR" },
            new IsoCountry { IsoCode="cu", Name="Cuba",                                     LangCode="ES-CU" },
            new IsoCountry { IsoCode="cy", Name="Cyprus",                                   LangCode="EL-CY" },
            new IsoCountry { IsoCode="cz", Name="Czech Republic",                           LangCode="CS" },
            new IsoCountry { IsoCode="dk", Name="Denmark",                                  LangCode="DA" },
            new IsoCountry { IsoCode="dj", Name="Djibouti",                                 LangCode="DJ" },
            new IsoCountry { IsoCode="dm", Name="Dominica",                                 LangCode="DM" },
            new IsoCountry { IsoCode="do", Name="Dominican Republic",                       LangCode="ES-DO" },
            new IsoCountry { IsoCode="ec", Name="Ecuador",                                  LangCode="ES-EC" },
            new IsoCountry { IsoCode="eg", Name="Egypt",                                    LangCode="AR-EG" },
            new IsoCountry { IsoCode="sv", Name="El Salvador",                              LangCode="ES-SV" },
            new IsoCountry { IsoCode="gq", Name="Equatorial Guinea",                        LangCode="ES-GQ" },
            new IsoCountry { IsoCode="er", Name="Eritrea",                                  LangCode="ER" },
            new IsoCountry { IsoCode="ee", Name="Estonia",                                  LangCode="ET" },
            new IsoCountry { IsoCode="sz", Name="Eswatini",                                 LangCode="SS" },
            new IsoCountry { IsoCode="et", Name="Ethiopia",                                 LangCode="AM-ET" },
            new IsoCountry { IsoCode="fj", Name="Fiji",                                     LangCode="FJ" },
            new IsoCountry { IsoCode="fi", Name="Finland",                                  LangCode="FI" },
            new IsoCountry { IsoCode="fr", Name="France",                                   LangCode="FR" },
            new IsoCountry { IsoCode="ga", Name="Gabon",                                    LangCode="GA" },
            new IsoCountry { IsoCode="gm", Name="Gambia",                                   LangCode="GM" },
            new IsoCountry { IsoCode="ge", Name="Georgia",                                  LangCode="KA" },
            new IsoCountry { IsoCode="de", Name="Germany",                                  LangCode="DE" },
            new IsoCountry { IsoCode="gh", Name="Ghana",                                    LangCode="GH" },
            new IsoCountry { IsoCode="gr", Name="Greece",                                   LangCode="EL" },
            new IsoCountry { IsoCode="gd", Name="Grenada",                                  LangCode="GD" },
            new IsoCountry { IsoCode="gt", Name="Guatemala",                                LangCode="ES-GT" },
            new IsoCountry { IsoCode="gn", Name="Guinea",                                   LangCode="GN" },
            new IsoCountry { IsoCode="gw", Name="Guinea-Bissau",                            LangCode="PT-GW" },
            new IsoCountry { IsoCode="gy", Name="Guyana",                                   LangCode="GY" },
            new IsoCountry { IsoCode="ht", Name="Haiti",                                    LangCode="FR-HT" },
            new IsoCountry { IsoCode="hn", Name="Honduras",                                 LangCode="ES-HN" },
            new IsoCountry { IsoCode="hu", Name="Hungary",                                  LangCode="HU" },
            new IsoCountry { IsoCode="is", Name="Iceland",                                  LangCode="IS" },
            new IsoCountry { IsoCode="in", Name="India",                                    LangCode="HI" },
            new IsoCountry { IsoCode="id", Name="Indonesia",                                LangCode="ID" },
            new IsoCountry { IsoCode="ir", Name="Iran",                                     LangCode="FA" },
            new IsoCountry { IsoCode="iq", Name="Iraq",                                     LangCode="AR-IQ" },
            new IsoCountry { IsoCode="ie", Name="Ireland",                                  LangCode="EN-IE" },
            new IsoCountry { IsoCode="il", Name="Israel",                                   LangCode="HE" },
            new IsoCountry { IsoCode="it", Name="Italy",                                    LangCode="IT" },
            new IsoCountry { IsoCode="jm", Name="Jamaica",                                  LangCode="JM" },
            new IsoCountry { IsoCode="jp", Name="Japan",                                    LangCode="JP" },
            new IsoCountry { IsoCode="jo", Name="Jordan",                                   LangCode="AR-JO" },
            new IsoCountry { IsoCode="kz", Name="Kazakhstan",                               LangCode="KK" },
            new IsoCountry { IsoCode="ke", Name="Kenya",                                    LangCode="SW-KE" },
            new IsoCountry { IsoCode="ki", Name="Kiribati",                                 LangCode="KI" },
            new IsoCountry { IsoCode="kp", Name="Korea (North)",                            LangCode="KO-KP" },
            new IsoCountry { IsoCode="kr", Name="Korea (South)",                            LangCode="KR" },
            new IsoCountry { IsoCode="kw", Name="Kuwait",                                   LangCode="AR-KW" },
            new IsoCountry { IsoCode="kg", Name="Kyrgyzstan",                               LangCode="KY" },
            new IsoCountry { IsoCode="la", Name="Laos",                                     LangCode="LO" },
            new IsoCountry { IsoCode="lv", Name="Latvia",                                   LangCode="LV" },
            new IsoCountry { IsoCode="lb", Name="Lebanon",                                  LangCode="AR-LB" },
            new IsoCountry { IsoCode="ls", Name="Lesotho",                                  LangCode="ST-LS" },
            new IsoCountry { IsoCode="lr", Name="Liberia",                                  LangCode="LR" },
            new IsoCountry { IsoCode="ly", Name="Libya",                                    LangCode="AR-LY" },
            new IsoCountry { IsoCode="li", Name="Liechtenstein",                            LangCode="DE-LI" },
            new IsoCountry { IsoCode="lt", Name="Lithuania",                                LangCode="LT" },
            new IsoCountry { IsoCode="lu", Name="Luxembourg",                               LangCode="LB" },
            new IsoCountry { IsoCode="mg", Name="Madagascar",                               LangCode="MG" },
            new IsoCountry { IsoCode="mw", Name="Malawi",                                   LangCode="MW" },
            new IsoCountry { IsoCode="my", Name="Malaysia",                                 LangCode="MS" },
            new IsoCountry { IsoCode="mv", Name="Maldives",                                 LangCode="DV" },
            new IsoCountry { IsoCode="ml", Name="Mali",                                     LangCode="ML" },
            new IsoCountry { IsoCode="mt", Name="Malta",                                    LangCode="MT" },
            new IsoCountry { IsoCode="mh", Name="Marshall Islands",                         LangCode="MH" },
            new IsoCountry { IsoCode="mr", Name="Mauritania",                               LangCode="AR-MR" },
            new IsoCountry { IsoCode="mu", Name="Mauritius",                                LangCode="MU" },
            new IsoCountry { IsoCode="mx", Name="Mexico",                                   LangCode="ES-MX" },
            new IsoCountry { IsoCode="fm", Name="Micronesia",                               LangCode="FM" },
            new IsoCountry { IsoCode="md", Name="Moldova",                                  LangCode="RO-MD" },
            new IsoCountry { IsoCode="mc", Name="Monaco",                                   LangCode="FR-MC" },
            new IsoCountry { IsoCode="mn", Name="Mongolia",                                 LangCode="MN" },
            new IsoCountry { IsoCode="me", Name="Montenegro",                               LangCode="SR-ME" },
            new IsoCountry { IsoCode="ma", Name="Morocco",                                  LangCode="AR-MA" },
            new IsoCountry { IsoCode="mz", Name="Mozambique",                               LangCode="PT-MZ" },
            new IsoCountry { IsoCode="mm", Name="Myanmar",                                  LangCode="MY" },
            new IsoCountry { IsoCode="na", Name="Namibia",                                  LangCode="NA" },
            new IsoCountry { IsoCode="nr", Name="Nauru",                                    LangCode="NR" },
            new IsoCountry { IsoCode="np", Name="Nepal",                                    LangCode="NE" },
            new IsoCountry { IsoCode="nl", Name="Netherlands",                              LangCode="NL" },
            new IsoCountry { IsoCode="nz", Name="New Zealand",                              LangCode="EN-NZ" },
            new IsoCountry { IsoCode="ni", Name="Nicaragua",                                LangCode="ES-NI" },
            new IsoCountry { IsoCode="ne", Name="Niger",                                    LangCode="NG" },
            new IsoCountry { IsoCode="ng", Name="Nigeria",                                  LangCode="EN-NG" },
            new IsoCountry { IsoCode="mk", Name="North Macedonia",                          LangCode="MK" },
            new IsoCountry { IsoCode="no", Name="Norway",                                   LangCode="NO" },
            new IsoCountry { IsoCode="om", Name="Oman",                                     LangCode="AR-OM" },
            new IsoCountry { IsoCode="pk", Name="Pakistan",                                 LangCode="UR" },
            new IsoCountry { IsoCode="pw", Name="Palau",                                    LangCode="PW" },
            new IsoCountry { IsoCode="pa", Name="Panama",                                   LangCode="ES-PA" },
            new IsoCountry { IsoCode="pg", Name="Papua New Guinea",                         LangCode="PG" },
            new IsoCountry { IsoCode="py", Name="Paraguay",                                 LangCode="ES-PY" },
            new IsoCountry { IsoCode="pe", Name="Peru",                                     LangCode="ES-PE" },
            new IsoCountry { IsoCode="ph", Name="Philippines",                              LangCode="TL" },
            new IsoCountry { IsoCode="pl", Name="Poland",                                   LangCode="PL" },
            new IsoCountry { IsoCode="pt", Name="Portugal",                                 LangCode="PT" },
            new IsoCountry { IsoCode="qa", Name="Qatar",                                    LangCode="AR-QA" },
            new IsoCountry { IsoCode="ro", Name="Romania",                                  LangCode="RO" },
            new IsoCountry { IsoCode="ru", Name="Russia",                                   LangCode="RU" },
            new IsoCountry { IsoCode="rw", Name="Rwanda",                                   LangCode="RW" },
            new IsoCountry { IsoCode="kn", Name="Saint Kitts and Nevis",                    LangCode="KN" },
            new IsoCountry { IsoCode="lc", Name="Saint Lucia",                              LangCode="LC" },
            new IsoCountry { IsoCode="vc", Name="Saint Vincent and the Grenadines",         LangCode="VC" },
            new IsoCountry { IsoCode="ws", Name="Samoa",                                    LangCode="SM" },
            new IsoCountry { IsoCode="sm", Name="San Marino",                               LangCode="IT-SM" },
            new IsoCountry { IsoCode="st", Name="Sao Tome and Principe",                    LangCode="PT-ST" },
            new IsoCountry { IsoCode="sa", Name="Saudi Arabia",                             LangCode="AR-SA" },
            new IsoCountry { IsoCode="sn", Name="Senegal",                                  LangCode="FR-SN" },
            new IsoCountry { IsoCode="rs", Name="Serbia",                                   LangCode="SR" },
            new IsoCountry { IsoCode="sc", Name="Seychelles",                               LangCode="SC" },
            new IsoCountry { IsoCode="sl", Name="Sierra Leone",                             LangCode="SL" },
            new IsoCountry { IsoCode="sg", Name="Singapore",                                LangCode="EN-SG" },
            new IsoCountry { IsoCode="sk", Name="Slovakia",                                 LangCode="SK" },
            new IsoCountry { IsoCode="si", Name="Slovenia",                                 LangCode="SL-SI" },
            new IsoCountry { IsoCode="sb", Name="Solomon Islands",                          LangCode="SB" },
            new IsoCountry { IsoCode="so", Name="Somalia",                                  LangCode="SO" },
            new IsoCountry { IsoCode="za", Name="South Africa",                             LangCode="AF-ZA" },
            new IsoCountry { IsoCode="ss", Name="South Sudan",                              LangCode="EN-SS" },
            new IsoCountry { IsoCode="es", Name="Spain",                                    LangCode="ES" },
            new IsoCountry { IsoCode="lk", Name="Sri Lanka",                                LangCode="SI" },
            new IsoCountry { IsoCode="sd", Name="Sudan",                                    LangCode="AR-SD" },
            new IsoCountry { IsoCode="sr", Name="Suriname",                                 LangCode="NL-SR" },
            new IsoCountry { IsoCode="se", Name="Sweden",                                   LangCode="SV" },
            new IsoCountry { IsoCode="ch", Name="Switzerland",                              LangCode="DE-CH" },
            new IsoCountry { IsoCode="sy", Name="Syria",                                    LangCode="AR-SY" },
            new IsoCountry { IsoCode="tw", Name="Taiwan",                                   LangCode="ZH-TW" },
            new IsoCountry { IsoCode="tj", Name="Tajikistan",                               LangCode="TG" },
            new IsoCountry { IsoCode="tz", Name="Tanzania",                                 LangCode="SW-TZ" },
            new IsoCountry { IsoCode="th", Name="Thailand",                                 LangCode="TH" },
            new IsoCountry { IsoCode="tl", Name="Timor-Leste",                              LangCode="PT-TL" },
            new IsoCountry { IsoCode="tg", Name="Togo",                                     LangCode="FR-TG" },
            new IsoCountry { IsoCode="to", Name="Tonga",                                    LangCode="TO" },
            new IsoCountry { IsoCode="tt", Name="Trinidad and Tobago",                      LangCode="TT" },
            new IsoCountry { IsoCode="tn", Name="Tunisia",                                  LangCode="AR-TN" },
            new IsoCountry { IsoCode="tr", Name="Turkey",                                   LangCode="TR" },
            new IsoCountry { IsoCode="tm", Name="Turkmenistan",                             LangCode="TK" },
            new IsoCountry { IsoCode="tv", Name="Tuvalu",                                   LangCode="TV" },
            new IsoCountry { IsoCode="ug", Name="Uganda",                                   LangCode="SW-UG" },
            new IsoCountry { IsoCode="ua", Name="Ukraine",                                  LangCode="UK" },
            new IsoCountry { IsoCode="ae", Name="United Arab Emirates",                     LangCode="AR-AE" },
            new IsoCountry { IsoCode="gb", Name="United Kingdom",                           LangCode="EN-GB" },
            new IsoCountry { IsoCode="us", Name="United States",                            LangCode="EN" },
            new IsoCountry { IsoCode="uy", Name="Uruguay",                                  LangCode="ES-UY" },
            new IsoCountry { IsoCode="uz", Name="Uzbekistan",                               LangCode="UZ" },
            new IsoCountry { IsoCode="vu", Name="Vanuatu",                                  LangCode="BI" },
            new IsoCountry { IsoCode="ve", Name="Venezuela",                                LangCode="ES-VE" },
            new IsoCountry { IsoCode="vn", Name="Vietnam",                                  LangCode="VI" },
            new IsoCountry { IsoCode="ye", Name="Yemen",                                    LangCode="AR-YE" },
            new IsoCountry { IsoCode="zm", Name="Zambia",                                   LangCode="EN-ZM" },
            new IsoCountry { IsoCode="zw", Name="Zimbabwe",                                 LangCode="EN-ZW" },
        };
    }
}
